# Generated by Django 5.0 on 2023-12-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('time_of_distribution', models.DateTimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('periodicity', models.DurationField(blank=True, null=True, verbose_name='Периодичность')),
                ('status', models.SmallIntegerField(choices=[(1, 'Создана'), (2, 'Запущена'), (3, 'Завершена')], default=1, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mail', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('text_mail', models.TextField(verbose_name='Тело письма')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandmail.mailsand', verbose_name='Название рассылки')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
