# Generated by Django 4.2 on 2024-01-30 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Ф.И.О.')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Почта клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailSand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('status', models.SmallIntegerField(choices=[(1, 'Создана'), (2, 'Запущена'), (3, 'Завершена')], default=1, verbose_name='Статус рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=10, verbose_name='Периодичность')),
                ('start_sand', models.TimeField(default=datetime.time(10, 0), verbose_name='Время начала рассылки')),
                ('end_send', models.TimeField(default=datetime.time(11, 0), verbose_name='Время окончания рассылки')),
                ('name_mail', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('text_mail', models.TextField(verbose_name='Текст письма')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки письма')),
                ('owner', models.ManyToManyField(to='sandmail.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-pk'],
                'permissions': [('set_status', 'can_deactivate_send')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[(1, 'Успешно'), (2, 'Не успешно')], max_length=20, verbose_name='Статус отправки')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandmail.mailsand', verbose_name='Название рассылки')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
