# Generated by Django 5.0 on 2023-12-11 18:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Ф.И.О.')),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='Почта клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиеты',
            },
        ),
        migrations.RemoveField(
            model_name='mailsand',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='mailsand',
            name='end_send',
            field=models.TimeField(default=datetime.time(11, 0), verbose_name='Время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailsand',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=10, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='mailsand',
            name='start_sand',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Время начала рассылки'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(max_length=10, verbose_name='Статус отправки')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandmail.mailsand', verbose_name='Название рассылки')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
