# Generated by Django 5.0 on 2023-12-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandmail', '0002_client_remove_mailsand_periodicity_mailsand_end_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsand',
            name='time_of_distribution',
        ),
    ]
