# Generated by Django 5.0 on 2023-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandmail', '0003_remove_mailsand_time_of_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsand',
            name='name_mail',
            field=models.CharField(default=1, max_length=150, verbose_name='Тема письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailsand',
            name='text_mail',
            field=models.TextField(default=1, verbose_name='Текст письма'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MailText',
        ),
    ]
