# Generated by Django 4.2 on 2024-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandmail', '0003_remove_mailsand_owner_mailsand_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailsand',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailsand',
            name='owner',
            field=models.ManyToManyField(to='sandmail.client', verbose_name='Клиенты'),
        ),
    ]
