# Generated by Django 5.0 on 2023-12-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandmail', '0004_mailsand_name_mail_mailsand_text_mail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsand',
            options={'ordering': ['-pk'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
